version: '3.7'

services:
  web:
    build: ../ask_gulyachenkov
    command: gunicorn ask_gulyachenkov.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./../ask_gulyachenkov/:/Users/dmitrijgulacenkov/Downloads/ask_gulyachenkov
    expose:
      - 8000
    env_file:
      - ./.env.dev

  nginx:
    build: ./nginx
    ports:
      - 8090:80
    depends_on:
      - web


#    depends_on:
#      - db
#db  db:
#    image: postgres:12.0-alpine
#    volumes:
#      - postgres_data:/var/lib/postgresql/data/
#    environment:
#      - POSTGRES_USER=hello_django
#      - POSTGRES_PASSWORD=hello_django
#      - POSTGRES_DB=hello_django_dev
#
#volumes:
#  postgres_data:

